### ISSUE TITLE
mc_demo crashes

### ISSUE THREAD

**Issue by michael-betz** [missionpinball/mpf-examples#1]
Hi, I'm having some trouble running the example projects. In particular the `mc_demo` crashes, which I thought is already a v0.30 compatible project (correct me if I'm wrong)

My current installation is from `pip install`:
mpf-mc:  0.30.0.dev902

I get this error when running:
`mpf mc ./mc_demo/`

``` python
INFO : kivy : Base: Start application main loop
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/michael/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michael/anaconda3/lib/python3.5/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
    _device = Device(_fn)
  File "/home/michael/anaconda3/lib/python3.5/site-packages/kivy/lib/mtdev.py", line 131, in __init__
    self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
PermissionError: [Errno 13] Permission denied: '/dev/input/event6'

INFO : kivy : Base: Leaving application in progress...
Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.5/site-packages/mpfmc/config_collections/widget.py", line 63, in process_widget
    config['_widget_cls'] = Widget.type_map[config['type']]
  File "/home/michael/anaconda3/lib/python3.5/site-packages/mpf/core/case_insensitive_dict.py", line 14, in __getitem__
    return super().__getitem__(self.__class__.lower(key))
KeyError: 'rise_in'
```

**Comment by toomanybrians** [comment]
You're correct that mc_demo is a 0.30 demo. However it was built on a much earlier build of 0.30, and has not been updated for the latest. So I'm going to keep this issue open because it's on our todo list to refresh the demo and make it work again.

**Comment by michael-betz** [comment]
Ah I see, thanks for the clarification. 
Could you point me to some example code for the current version? In particular on how to use the slide widgets. 

If there is no such thing yet, don't worry, I can still dig into the unit-tests ;)

Cheers
yfl

**Comment by jabdoa2** [comment]
Just look at the unit tests folder: https://github.com/missionpinball/mpf-mc/tree/dev/mpfmc/tests/machine_files. They work for sure.

Otherwise have a look at the documentation of 0.30 (which is still growing): http://docs.missionpinball.com/0.30/

**Comment by toomanybrians** [comment]
this is done
