### ISSUE TITLE
[demo_man] upgrade to mpf version 0.53.x

### ISSUE THREAD

**Issue by arthurlutz** [missionpinball/mpf-examples#11]
```
Exception in callback EventManager._done(<Task finishe... not found',)>)
handle: <Handle EventManager._done(<Task finishe... not found',)>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 691, in _done
    future.result()
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 608, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/home/arthur/local/mpf/mpf/mpf/core/mode.py", line 212, in start
    **item.kwargs)
  File "/home/arthur/local/mpf/mpf/mpf/core/config_player.py", line 203, in mode_start
    event_keys = self.register_player_events(config, mode, priority)
  File "/home/arthur/local/mpf/mpf/mpf/config_players/plugin_player.py", line 57, in register_player_events
    self.bcp_client = self._get_bcp_client(config)
  File "/home/arthur/local/mpf/mpf/mpf/config_players/plugin_player.py", line 34, in _get_bcp_client
    "bcp connection {} not found".format(client_name))
AssertionError: bcp connection local_display not found
Shutdown because of an exception:
Runtime Exception
Traceback (most recent call last):
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 658, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "/home/arthur/local/mpf/mpf/mpf/core/text_ui.py", line 311, in _update_player
    player_vars.pop('ball')
KeyError: 'ball'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arthur/local/mpf/mpf/mpf/core/machine.py", line 757, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 739, in process_event_queue
    **event[3])
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 704, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "/home/arthur/local/mpf/mpf/mpf/core/events.py", line 660, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method TextUi._update_player of <mpf.core.text_ui.TextUi object at 0x7f2257f0c708>>, priority=1, kwargs={}, key=UUID('c7d51e4c-6f59-4605-b401-7fdf961cdf24'), condition=None, blocking_facility=None) for event player_number
MPF run loop ended.
```

When trying to start demo_man on version 0.53.0

```
pip list | grep mpf
mpf              0.53.0.dev59 /home/arthur/local/mpf/mpf        
mpf-mc           0.53.0.dev10 /home/arthur/local/mpf/mpf-mc     
mpf-monitor      0.53.0.dev1  /home/arthur/local/mpf/mpf-monitor

```

**Comment by jabdoa2** [comment]
Try "mpf both -t" to disable the text ui. We will fix the bug in a few days.

**Comment by arthurlutz** [comment]
@jabdoa2 thanks for the quick response. Using `mpf both -t` gets the display going but gets stuck on "Loading assets : 100%", S key doesn't do anything, etc. 

Here is the end of the logs : 

```
AssetManager: Loading assets: 23/23 (100%)
EventManager: Event: ======'init_done'====== Args={}
mpfmc: SlidePlayer: Play called with settings={'slides': {asset_status-None-None: {'priority': None, 'target': None, 'background_color': [0.0, 0.0, 0.0, 1.0], 'show': True, 'force': False, 'expire': None, 'slide': None, 'tokens': {}, 'action': 'play', 'transition': None, 'transition_out': None}}}
EventManager: Event: ======'slide_asset_status_created'====== Args={}
mpfmc: SlidePlayer: Play called with settings={'slides': {asset_status-None-None: {'priority': None, 'target': None, 'background_color': [0.0, 0.0, 0.0, 1.0], 'show': True, 'force': False, 'expire': None, 'slide': None, 'tokens': {}, 'action': 'play', 'transition': None, 'transition_out': None}}}
EventManager: Event: ======'slide_asset_status_removed'====== Args={}
EventManager: Event: ======'slide_asset_status_created'====== Args={}
MPF-MC BCP Server: Starting up on localhost port 5050
MPF-MC BCP Server: Waiting for a connection...
EventManager: Event: ======'slide_asset_status_active'====== Args={}
EventManager: Event: ======'client_disconnected'====== Args={'host': '127.0.0.1', 'port': 5050}
```

**Comment by jabdoa2** [comment]
Looks like mc is working. What is in the mpf log? I guess there is an issue there

**Comment by jabdoa2** [comment]
Did you get it working?
